### ISSUE TITLE
Missing npm dependencies

### ISSUE THREAD

**Issue by justinsthomas** [steelbrain/process-communication#3]
Long story short, there are linter packages for Atom that rely on this npm module. I cloned this repo and tried to build it locally, and npm is erroring out on a 404 on `https://registry.npmjs.org/babel-preset-steelbrain-legacy`. Is there an acceptable alternative to that babel config, or are there plans to republish it to npm to unbreak this package?

**Error messaging in terminal:**
npm ERR! node v4.2.4
npm ERR! npm  v2.15.1
npm ERR! code E404

npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/babel-preset-steelbrain-legacy
npm ERR! 404 
npm ERR! 404 'babel-preset-steelbrain-legacy' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'process-communication'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

**Comment by steelbrain** [comment]
Oh yeah, but that's just a dev dependency, end users shouldn't be affected by this.
I'll push the changes removing it

**Comment by steelbrain** [comment]
As a side note, you could've just `npm-install`ed it, you'll have to build it manually when you clone the repo
